# Use the base Node.js 14 image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy your application code into the container
COPY . /app

# Run npm install
RUN npm install

# Command to run your application
# CMD ["npm", "start"]

# Expose the necessary port
# EXPOSE 3000
